タグ確認

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -24,6 +24,16 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ github.event.inputs.tag }}
+
+      # タグが存在するかチェック
+      - name: Check Tag
+        if: ${{ github.event.inputs.tag != '' }}
+        run: |
+          git fetch --tags
+          if [ -z "$(git tag -l ${{ github.event.inputs.tag }})" ]; then
+            echo "Tag not found"
+            exit 1
+          fi
       
       - name: Check files and pwd
         working-directory: ${{ env.SRC_DIR }}
